# .streamlit/secrets.toml  ‚Üê make sure the path is exactly this

[gcp_service_account]
type = "service_account"
project_id = "still-emissary-471712-s5"
private_key_id = "c1964e147a8b03eca23ef259a69af358687f5e59"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCvFnX2h/if1bql
n9E2CYDGh45AbukY8ZvYJWZ86FkxR5U5Br4d1h9/Cf1BySCDc1+cG7mQ8pYvS6
NHkDsBx5FErsvqKFAG5HpzXfnh/Yuq/qsmLR3eYwR997z1TzgZ4uM8ftsQp9Rww
nYGFrqSwKFueytKmowgZryeTgJXR09HEYJ06bJTH0tZg/2s+r+gMhI2FYGT0yst
nGHAUQFy30Mmdz1Nd5-bahCLXg4Ftm1w/cCFX791qBaUPeJrRy1fB60f+CJD1m8n
n5SUQ7/j9s-aW9ay0Ehj8Dp5wTXUjEzK1wWcgXgz+i+JUwembz5BJtED4z5232ZU
n4CZVC4pLagMBAECgYEAvsuislH87r4a93c2dw052vdn06dUL9IBKloUIkUjQ
nJyIixuRz50MdVnvFOCfS16nVHt6kgqGMJFG1AFKjdxmkFBLsFb4pPgoY7nzpg9f
ndO81bO0vPU1IBrkDsbfXyPcNAC1/pbtFCF1ED0252oQ9IC5xEq0xrrVnBgSDNb
nbkK13Kz7THKQVh3b0bPrQ8GFsrowjumUt+28+eMSB280yUEi1aPQLpEZ+1cGsAwd
nCV2eBw3XEHr09HtuegQ/Rvn9UeJh+gHvLu0wEwK0RjmdU70wmxHHOre6PM1k6M
nyMOExr8i62mHuaF83/GiL72aFCSFDnCuIc3RVUQM70kBg0D5Ra17Ik1gqoUDQcI9
n3z0F5moo9Q6G/7gc8ugfARsDS4nELgm6vnv8F-JDTMkuySaxk00bIIN8pLUQdbCv
ny1VGhvD33sRNBeVU+/3zHxTdq8rYZxwf+/FZFPYNItTqenFf3kFtL1ED6VM4129j
n3hm+QAHyfUYtsGKQ/D6zk+7RxQK8gQD1hk3p78Rs4b1+EPS14mZSPaeuhj1HACTn
+ENITQzrFpA9Q1rVH8Ubj1CLLKbjTbR96JuI1ddyu+6s1SBa9H9
-----END PRIVATE KEY-----"""
client_email = "mycarlog@still-emissary-471712-s5.iam.gserviceaccount.com"
client_id = "1112195814928032149246"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/mycarlog%40still-emissary-471712-s5.iam.gserviceaccount.com"
